# Generated by Django 3.2.3 on 2021-07-20 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCommServer', '0005_auto_20160908_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycommdevice',
            name='createdDate',
            field=models.DateTimeField(verbose_name='2021-07-21 00:35:47'),
        ),
        migrations.AlterField(
            model_name='mycommdevice',
            name='imei',
            field=models.TextField(max_length=25, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mycommmsg',
            name='receivedTime',
            field=models.DateTimeField(verbose_name='2021-07-21 00:35:47'),
        ),
        migrations.AlterField(
            model_name='usermsg',
            name='receivedTime',
            field=models.DateTimeField(verbose_name='2021-07-21 00:35:47'),
        ),
    ]
